#!/bin/sh
### BEGIN INIT INFO
# Provides:          auto-dhcp
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Auto DHCP client
# Description:       Auto-detect network interface and obtain DHCP lease
### END INIT INFO

DAEMON=/usr/local/sbin/auto-dhcp
NAME=auto-dhcp

[ -x "$DAEMON" ] || exit 0

case "$1" in
    start)
        echo "Starting $NAME..."
        $DAEMON start
        ;;
    stop)
        echo "Stopping $NAME..."
        $DAEMON stop
        ;;
    restart|force-reload)
        echo "Restarting $NAME..."
        $DAEMON restart
        ;;
    status)
        if ip -4 addr show | grep -q 'inet .*scope global'; then
            echo "$NAME: network is up"
            exit 0
        else
            echo "$NAME: no network"
            exit 1
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}"
        exit 1
        ;;
esac

exit 0
