#!/bin/bash

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -eo pipefail

BUILD_SCRIPT=$1

sudo bin/provision-apt-get-update

if [ "$GIT_BRANCH" = 'master' ]; then
  sudo bin/provision-apt-get-upgrade
else
  echo 'Skipping apt-get upgrade (executed only in the master branch)'
fi

sudo bin/provision-apt-get-install

mkdir -p Remaster

rm -rf Output

scripts/build-stage "$BUILD_SCRIPT-00"
scripts/build-stage "$BUILD_SCRIPT-01"
scripts/build-stage "$BUILD_SCRIPT-02"
