#!/bin/bash

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -eo pipefail

BASE_SCRIPT='defaults-Xfce-ahs-github'

mkdir -p log
TIME_STAMP_LOCAL=`date -u +%Y-%m%d-%H%M%S`
LOG_FILE="log/$BASE_SCRIPT-$TIME_STAMP_LOCAL.txt"
scripts/build "$BASE_SCRIPT" 2>&1 | tee "$LOG_FILE"

